apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v14.2.8
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook
  mon:
    count: 3
    allowMultiplePerNode: false
  dashboard:
    enabled: true
    ssl: true
  monitoring:
    enabled: true
  network:
    hostNetwork: true
  crashCollector:
    disable: false
  placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: role
              operator: In
              values:
              - storage-node
      podAffinity:
      podAntiAffinity:
      tolerations:
      - key: storage-node
        operator: Exists
  storage:
    useAllNodes: false
    useAllDevices: false
    config:
       databaseSizeMB: "1024"
       journalSizeMB: "1024"
    nodes:
    - name: "ocp-worker0.ocp.zyl.io"
      devices:
      - name: "vdc"
    - name: "ocp-worker1.ocp.zyl.io"
      devices: 
      - name: "vdc"
    - name: "ocp-worker2.ocp.zyl.io"
      devices: 
      - name: "vdc"
