{
 "title": "Hello App Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(flask_exporter_info{namespace!=''}, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "http request",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "flask http request count per second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (job) (error:flask_http_request_count:rate1m{namespace=\"$namespace\"})",
       "legendFormat": "{{job}}"
      },
      {
       "expr": "sum by (job) (success:flask_http_request_count:rate1m{namespace=\"$namespace\"})",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "flask http request count per min",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (job) (total:flask_http_request_count:inc1m{namespace=\"$namespace\"})",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "avg success http request time(sec)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (job) (avg:success:flask_http_request_time:rate1m{namespace=\"$namespace\"})",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "success percent http request time le 0.25s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (job,pod) (success:percent:flask_http_request_time_le_025:inc1m{namespace=\"$namespace\"})",
       "legendFormat": "{{job}}: {{pod}}"
      }
     ]
    },
    {
     "title": "90% success http request time le (s)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (job,pod) (success:quantile:90:flask_http_request_time{namespace=\"$namespace\"})",
       "legendFormat": "{{job}}: {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "cpu and memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "process cpu utilisation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (job,pod) (job:process_cpu_utilisation:rate1m{namespace=\"$namespace\"})",
       "legendFormat": "{{job}}: {{pod}}"
      }
     ]
    },
    {
     "title": "process resident memory bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (job,pod) (process_resident_memory_bytes{namespace=\"$namespace\"})",
       "legendFormat": "{{job}}: {{pod}}"
      }
     ]
    }
   ]
  }
 ]
}